//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace AuthControl.XSD {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class dsUsersPermissions : DataSet {
        
        private UsersPermissionsDataTable tableUsersPermissions;
        
        public dsUsersPermissions() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected dsUsersPermissions(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["UsersPermissions"] != null)) {
                    this.Tables.Add(new UsersPermissionsDataTable(ds.Tables["UsersPermissions"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public UsersPermissionsDataTable UsersPermissions {
            get {
                return this.tableUsersPermissions;
            }
        }
        
        public override DataSet Clone() {
            dsUsersPermissions cln = ((dsUsersPermissions)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["UsersPermissions"] != null)) {
                this.Tables.Add(new UsersPermissionsDataTable(ds.Tables["UsersPermissions"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableUsersPermissions = ((UsersPermissionsDataTable)(this.Tables["UsersPermissions"]));
            if ((this.tableUsersPermissions != null)) {
                this.tableUsersPermissions.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "dsUsersPermissions";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/dsUsersPermissions.xsd";
            this.Locale = new System.Globalization.CultureInfo("ru-RU");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableUsersPermissions = new UsersPermissionsDataTable();
            this.Tables.Add(this.tableUsersPermissions);
        }
        
        private bool ShouldSerializeUsersPermissions() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void UsersPermissionsRowChangeEventHandler(object sender, UsersPermissionsRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class UsersPermissionsDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnDescription;
            
            private DataColumn columnParentPermissionID;
            
            private DataColumn columnUserPermissionID;
            
            private DataColumn columnUserID;
            
            private DataColumn columnPermissionID;
            
            private DataColumn columnAllow;
            
            private DataColumn columnExpr1;
            
            private DataColumn columnShowOrder;
            
            internal UsersPermissionsDataTable() : 
                    base("UsersPermissions") {
                this.InitClass();
            }
            
            internal UsersPermissionsDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn DescriptionColumn {
                get {
                    return this.columnDescription;
                }
            }
            
            internal DataColumn ParentPermissionIDColumn {
                get {
                    return this.columnParentPermissionID;
                }
            }
            
            internal DataColumn UserPermissionIDColumn {
                get {
                    return this.columnUserPermissionID;
                }
            }
            
            internal DataColumn UserIDColumn {
                get {
                    return this.columnUserID;
                }
            }
            
            internal DataColumn PermissionIDColumn {
                get {
                    return this.columnPermissionID;
                }
            }
            
            internal DataColumn AllowColumn {
                get {
                    return this.columnAllow;
                }
            }
            
            internal DataColumn Expr1Column {
                get {
                    return this.columnExpr1;
                }
            }
            
            internal DataColumn ShowOrderColumn {
                get {
                    return this.columnShowOrder;
                }
            }
            
            public UsersPermissionsRow this[int index] {
                get {
                    return ((UsersPermissionsRow)(this.Rows[index]));
                }
            }
            
            public event UsersPermissionsRowChangeEventHandler UsersPermissionsRowChanged;
            
            public event UsersPermissionsRowChangeEventHandler UsersPermissionsRowChanging;
            
            public event UsersPermissionsRowChangeEventHandler UsersPermissionsRowDeleted;
            
            public event UsersPermissionsRowChangeEventHandler UsersPermissionsRowDeleting;
            
            public void AddUsersPermissionsRow(UsersPermissionsRow row) {
                this.Rows.Add(row);
            }
            
            public UsersPermissionsRow AddUsersPermissionsRow(string Description, int ParentPermissionID, int UserID, int PermissionID, bool Allow, int ShowOrder) {
                UsersPermissionsRow rowUsersPermissionsRow = ((UsersPermissionsRow)(this.NewRow()));
                rowUsersPermissionsRow.ItemArray = new object[] {
                        Description,
                        ParentPermissionID,
                        null,
                        UserID,
                        PermissionID,
                        Allow,
                        null,
                        ShowOrder};
                this.Rows.Add(rowUsersPermissionsRow);
                return rowUsersPermissionsRow;
            }
            
            public UsersPermissionsRow FindByUserPermissionIDExpr1(int UserPermissionID, int Expr1) {
                return ((UsersPermissionsRow)(this.Rows.Find(new object[] {
                            UserPermissionID,
                            Expr1})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                UsersPermissionsDataTable cln = ((UsersPermissionsDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new UsersPermissionsDataTable();
            }
            
            internal void InitVars() {
                this.columnDescription = this.Columns["Description"];
                this.columnParentPermissionID = this.Columns["ParentPermissionID"];
                this.columnUserPermissionID = this.Columns["UserPermissionID"];
                this.columnUserID = this.Columns["UserID"];
                this.columnPermissionID = this.Columns["PermissionID"];
                this.columnAllow = this.Columns["Allow"];
                this.columnExpr1 = this.Columns["Expr1"];
                this.columnShowOrder = this.Columns["ShowOrder"];
            }
            
            private void InitClass() {
                this.columnDescription = new DataColumn("Description", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDescription);
                this.columnParentPermissionID = new DataColumn("ParentPermissionID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnParentPermissionID);
                this.columnUserPermissionID = new DataColumn("UserPermissionID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnUserPermissionID);
                this.columnUserID = new DataColumn("UserID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnUserID);
                this.columnPermissionID = new DataColumn("PermissionID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPermissionID);
                this.columnAllow = new DataColumn("Allow", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnAllow);
                this.columnExpr1 = new DataColumn("Expr1", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnExpr1);
                this.columnShowOrder = new DataColumn("ShowOrder", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnShowOrder);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnUserPermissionID,
                                this.columnExpr1}, true));
                this.columnDescription.AllowDBNull = false;
                this.columnUserPermissionID.AutoIncrement = true;
                this.columnUserPermissionID.AllowDBNull = false;
                this.columnUserPermissionID.ReadOnly = true;
                this.columnUserID.AllowDBNull = false;
                this.columnPermissionID.AllowDBNull = false;
                this.columnAllow.AllowDBNull = false;
                this.columnExpr1.AutoIncrement = true;
                this.columnExpr1.AllowDBNull = false;
                this.columnExpr1.ReadOnly = true;
            }
            
            public UsersPermissionsRow NewUsersPermissionsRow() {
                return ((UsersPermissionsRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new UsersPermissionsRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(UsersPermissionsRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.UsersPermissionsRowChanged != null)) {
                    this.UsersPermissionsRowChanged(this, new UsersPermissionsRowChangeEvent(((UsersPermissionsRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.UsersPermissionsRowChanging != null)) {
                    this.UsersPermissionsRowChanging(this, new UsersPermissionsRowChangeEvent(((UsersPermissionsRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.UsersPermissionsRowDeleted != null)) {
                    this.UsersPermissionsRowDeleted(this, new UsersPermissionsRowChangeEvent(((UsersPermissionsRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.UsersPermissionsRowDeleting != null)) {
                    this.UsersPermissionsRowDeleting(this, new UsersPermissionsRowChangeEvent(((UsersPermissionsRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveUsersPermissionsRow(UsersPermissionsRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class UsersPermissionsRow : DataRow {
            
            private UsersPermissionsDataTable tableUsersPermissions;
            
            internal UsersPermissionsRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableUsersPermissions = ((UsersPermissionsDataTable)(this.Table));
            }
            
            public string Description {
                get {
                    return ((string)(this[this.tableUsersPermissions.DescriptionColumn]));
                }
                set {
                    this[this.tableUsersPermissions.DescriptionColumn] = value;
                }
            }
            
            public int ParentPermissionID {
                get {
                    try {
                        return ((int)(this[this.tableUsersPermissions.ParentPermissionIDColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUsersPermissions.ParentPermissionIDColumn] = value;
                }
            }
            
            public int UserPermissionID {
                get {
                    return ((int)(this[this.tableUsersPermissions.UserPermissionIDColumn]));
                }
                set {
                    this[this.tableUsersPermissions.UserPermissionIDColumn] = value;
                }
            }
            
            public int UserID {
                get {
                    return ((int)(this[this.tableUsersPermissions.UserIDColumn]));
                }
                set {
                    this[this.tableUsersPermissions.UserIDColumn] = value;
                }
            }
            
            public int PermissionID {
                get {
                    return ((int)(this[this.tableUsersPermissions.PermissionIDColumn]));
                }
                set {
                    this[this.tableUsersPermissions.PermissionIDColumn] = value;
                }
            }
            
            public bool Allow {
                get {
                    return ((bool)(this[this.tableUsersPermissions.AllowColumn]));
                }
                set {
                    this[this.tableUsersPermissions.AllowColumn] = value;
                }
            }
            
            public int Expr1 {
                get {
                    return ((int)(this[this.tableUsersPermissions.Expr1Column]));
                }
                set {
                    this[this.tableUsersPermissions.Expr1Column] = value;
                }
            }
            
            public int ShowOrder {
                get {
                    try {
                        return ((int)(this[this.tableUsersPermissions.ShowOrderColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableUsersPermissions.ShowOrderColumn] = value;
                }
            }
            
            public bool IsParentPermissionIDNull() {
                return this.IsNull(this.tableUsersPermissions.ParentPermissionIDColumn);
            }
            
            public void SetParentPermissionIDNull() {
                this[this.tableUsersPermissions.ParentPermissionIDColumn] = System.Convert.DBNull;
            }
            
            public bool IsShowOrderNull() {
                return this.IsNull(this.tableUsersPermissions.ShowOrderColumn);
            }
            
            public void SetShowOrderNull() {
                this[this.tableUsersPermissions.ShowOrderColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class UsersPermissionsRowChangeEvent : EventArgs {
            
            private UsersPermissionsRow eventRow;
            
            private DataRowAction eventAction;
            
            public UsersPermissionsRowChangeEvent(UsersPermissionsRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public UsersPermissionsRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
